### PR TITLE
Fixing uncaught expection with missing partial

### PR DESCRIPTION
**Pull request by bnormington**
Forked this project from kdmny account and brought it into goodwaygroup.
Added a try catch block in the render method to capture an unhandled exception with missing partials. Added a new unit test to capture my changes but the old tests were previously/currently failing do to the previous changes.

### CODE REVIEW

**Comment by clok** [comment]
@bnormington Where is the change to the `package.json` file with the module pointed at the forked repo?

**Comment by bnormington** [comment]
That would be in the golive project which will point to this new repo and tag. (when I create that tag after the PR is merged.)

**Comment by clok** [comment]
I am dumb... was assuming this was golive. Did not read the repo name. Doh!

**Review by clok — APPROVED** [review]
Looks solid.

**Pull request merged**
